src/Entity/Commande.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ApiResource()
 * @ORM\Entity(repositoryClass="App\Repository\CommandeRepository")
 */
class Commande
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Usager", inversedBy="commandes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $usager;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_commande;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $statut;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\LigneCommande", mappedBy="commande")
     */
    private $ligneCommandes;

    public function __construct()
    {
        $this->ligneCommandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsager(): ?Usager
    {
        return $this->usager;
    }

    public function setUsager(?Usager $usager): self
    {
        $this->usager = $usager;

        return $this;
    }

    public function getDateCommande(): ?\DateTimeInterface
    {
        return $this->date_commande;
    }

    public function setDateCommande(\DateTimeInterface $date_commande): self
    {
        $this->date_commande = $date_commande;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    /**
     * @return Collection|LigneCommande[]
     */
    public function getLigneCommandes(): Collection
    {
        return $this->ligneCommandes;
    }

    public function addLigneCommande(LigneCommande $ligneCommande): self
    {
        if (!$this->ligneCommandes->contains($ligneCommande)) {
            $this->ligneCommandes[] = $ligneCommande;
            $ligneCommande->getCommande($this);
        }

        return $this;
    }

    public function removeLigneCommande(LigneCommande $ligneCommande): self
    {
        if ($this->ligneCommandes->contains($ligneCommande)) {
            $this->ligneCommandes->removeElement($ligneCommande);
            // set the owning side to null (unless already changed)
            if ($ligneCommande->getCommande() === $this) {
                $ligneCommande->setCommande(null);
            }
        }

        return $this;
    }
}

src/Entity/Usager.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ApiResource()
 * @ORM\Entity(repositoryClass="App\Repository\UsagerRepository")
 */
class Usager implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\Email(
     *  message="L\'email {{ value }} n'est pas valide"
     * )
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     * @Assert\Length(
     *     min = 8,
     *     minMessage="Le mot de passe doit contenir un minimum de {{ limit }} caractères",
     * )
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commande", mappedBy="id_usager")
     */
    private $commandes;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * @return Collection|Commande[]
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setIdUsager($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->contains($commande)) {
            $this->commandes->removeElement($commande);
            // set the owning side to null (unless already changed)
            if ($commande->getIdUsager() === $this) {
                $commande->setIdUsager(null);
            }
        }

        return $this;
    }
}

src/Form/UsagerType.php
<?php

namespace App\Form;

use App\Entity\Usager;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class UsagerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email', EmailType::class)
            ->add('password', PasswordType::class, [
                'label' => 'Mot de passe'
            ])
            ->add('nom')
            ->add('prenom')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Usager::class,
        ]);
    }
}

src/Controller/UsagerController.php
<?php

namespace App\Controller;

use App\Entity\Categorie;
use App\Entity\Commande;
use App\Entity\Usager;
use App\Form\UsagerType;
use App\Repository\UsagerRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoder;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @Route("/{_locale}/usager")
 */
class UsagerController extends AbstractController
{
    /**
     * @var SessionInterface
     */
    private $session;

    public function __construct(SessionInterface $session)
    {
        $this->session = $session;
    }

    /**
     * @Route("/", name="usager_index", methods={"GET"})
     * @param UsagerRepository $usagerRepository
     * @return Response
     * @Security("has_role('ROLE_ADMIN')")
     */

    public function index(UsagerRepository $usagerRepository): Response
    {
        // Index sera utilisé pour l'administrateur plus tard

        return $this->render('usager/index.html.twig', [
            'usager' => $this->getDoctrine()->getRepository(Usager::class)->findOneById($this->session->get('usager')),
        ]);
    }

    /**
     * @Route("/new", name="usager_new", methods={"GET","POST"})
     * @param Request $request
     * @param UserPasswordEncoderInterface $passwordEncoder
     * @return Response
     */
    public function new(Request $request, UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $usager = new Usager();
        $form = $this->createForm(UsagerType::class, $usager);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            // Encryptage du mot de passe
            $usager->setPassword($passwordEncoder->encodePassword($usager,$usager->getPassword()));
            // Définition du rôle
            $usager->setRoles(["ROLE_CLIENT"]);
            $em->persist($usager);
            $em->flush();
            $this->session->set('usager', $usager->getId());
            $this->addFlash('success', 'Compte créé');

            return $this->redirectToRoute('app_login');
        }

        return $this->render('usager/new.html.twig', [
            'usager' => $usager,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/commande", name="commande", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function commandes(Request $request): Response
    {
        $commandes = $this->getDoctrine()->getRepository(Commande::class)->findBy(['usager' => $this->getUser()->getId()], ['date_commande' => 'DESC']);

        return $this->render('usager/commande.html.twig', [
            'usager' => $this->getUser(),
            'commandes' => $commandes,
        ]);
    }

    /**
     * @Route("/{id}", name="usager_show", methods={"GET","POST"})
     * @param Request $request
     * @param UserPasswordEncoderInterface $passwordEncoder
     * @param Usager $usager
     * @return Response
     */
    public function show(Request $request, UserPasswordEncoderInterface $passwordEncoder, Usager $usager): Response
    {
        $form_edit = $this->createForm(UsagerType::class, $usager);
        $form_edit->remove('email');
        $form_edit->remove('password');
        $form_edit->handleRequest($request);

        if ($form_edit->isSubmitted() && $form_edit->isValid()) {
            $em = $this->getDoctrine()->getManager();
            // Encryptage du mot de passe
            $usager->setPassword($passwordEncoder->encodePassword($usager,$usager->getPassword()));
            // Définition du rôle
            $usager->setRoles(["ROLE_CLIENT"]);
            $em->persist($usager);
            $em->flush();
            $this->session->set('usager', $usager->getId());

            return $this->redirectToRoute('usager_show', ['id' => $usager->getId()]);
        }

        return $this->render('usager/show.html.twig', [
            'usager' => $usager,
            'form' => $form_edit->createView(),
        ]);
    }

}

templates/usager/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-info">{{ 'buttonComfirm' | trans }}</button>
{{ form_end(form) }}

templates/usager/commande.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes commandes{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            {% for commande in commandes %}
                <div class="col-2">
                    <div class="card clickable" style="width: 18rem;">
                        <div class="card-body">
                            <h5 class="card-title">{{commande.dateCommande | date('d/m/Y \\ H:i') }}</h5>
                        </div>
                        <a class="btn btn-primary" data-toggle="collapse" href="#collapse{{ commande.id }}" aria-expanded="false" aria-controls="collapseExample">
                            <b>{{ 'showProducts' | trans }}</b>
                        </a>
                        <div class="collapse" id="collapse{{ commande.id }}">
                            <div class="card card-body">
                                {% for ligne in commande.ligneCommandes %}
                                    <div>
                                        {{ ligne.produit.libelle }} x{{ ligne.quantite }} ({{ ligne.prix }})
                                    </div>
                                {% endfor %}
                                <p>{{ 'orderedOn' | trans }} {{ commande.dateCommande | date('d/m/Y \\ H:i') }}</p>
                                <p>{{ 'Status' | trans }} : {{ commande.statut }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/usager/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Usager index{% endblock %}

{% block body %}
    <h1>Usager index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Email</th>
                <th>Roles</th>
                <th>Password</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
{#        {% for usager in usagers %}#}
        {% if usager is not empty %}
            <tr>
                <td>{{ usager.id }}</td>
                <td>{{ usager.email }}</td>
                <td>{{ usager.roles ? usager.roles|json_encode : '' }}</td>
                <td>{{ usager.password }}</td>
                <td>{{ usager.nom }}</td>
                <td>{{ usager.prenom }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endif %}
        </tbody>
    </table>

    <a href="{{ path('usager_new') }}">Create new</a>
{% endblock %}

templates/usager/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'store' | trans }}{% endblock %}

{% block body %}
    <div class="container">
        <div class="col-sm-12 col-md-6">
        <h1 class="h3 mb-3 font-weight-normal">{{ 'registration' | trans }}</h1>
        {{ include('usager/_form.html.twig') }}
        </div>
    </div>
{#    <a href="{{ path('usager_index') }}">back to list</a>#}
{% endblock %}

templates/usager/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'account' | trans }}{% endblock %}

{% block body %}
    <div class="container">
        <div class="col-sm-12 col-md-6">
        <h2>{{ usager.nom }} {{ usager.prenom }}</h2>
            <p>{{ usager.email }}</p>
            {{ include('usager/_form.html.twig') }}
        </div>
    </div>

{% endblock %}